{{- if .Values.cdcs.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl (.Values.cdcs.secret.name) . }}"
  namespace: {{ .Release.Namespace }}
type: generic
stringData:
  django_secret_key: {{ .Values.cdcs.secret.django_secret_key }}
{{- end }}