{{- if .Values.cdcs.persistence.media.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cdcs-pvc-media
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  {{-  if .Values.cdcs.persistence.media.storageClassName }}
  storageClassName: {{ .Values.cdcs.persistence.media.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cdcs.persistence.media.size }}
{{- end }}
